// Generated by CoffeeScript 1.12.4
var Row, setType;

setType = require("setType");

Row = function(db) {
  var self;
  self = function(attr) {
    return self._access(self, attr);
  };
  self._db = db;
  return setType(self, Row);
};

module.exports = Row;
