// Generated by CoffeeScript 2.3.1
var Database, Query, Table, TypeError, cache, isPlainObj, rethinkdb, utils;

isPlainObj = require('is-plain-object');

TypeError = require('type-error');

Database = require('./Database');

Table = require('./Table');

Query = require('./Query');

utils = require('./utils');

// Bind the possible query types.
utils.isQuery = utils.isQuery.bind(null, [Query, Table]);

cache = Object.create(null);

rethinkdb = function(options = {}) {
  var db, name;
  if (!isPlainObj(options)) {
    throw TypeError(Object, options);
  }
  name = options.name || 'test';
  if (db = cache[name]) {
    return db;
  }
  db = Database(name);
  cache[name] = db;
  return db;
};

module.exports = rethinkdb;
